name: Update
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0,12 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: |
          if [ "$(curl https://blog.yifangu.com/wp-json/wp/v2/posts?per_page=1 | jq -r '.[0].date_gmt')" != "$(cat _data/wordpress.json | jq -r '.[0].date_gmt')" ]; then
            curl 'https://blog.yifangu.com/wp-json/wp/v2/posts?per_page=5' > _data/wordpress.json
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A && git commit -m "Update Content - [Skip GitHub Action]" && git push || true
          fi
