name: Update
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0,12 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: |
          if [ "$(curl 'https://public-api.wordpress.com/rest/v1.1/sites/blog.yifangu.com/posts/?number=5' | jq -r .found)" != "$(cat _data/wordpress.json | jq -r .found)" ]; then
            curl 'https://public-api.wordpress.com/rest/v1.1/sites/blog.yifangu.com/posts/?number=5' > _data/wordpress.json
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A && git commit -m "Update Content - [Skip GitHub Action]" && git push || true
          fi
